<a href="https://colab.research.google.com/github/Pravallika1234uppala/PythonLibraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NUMPY

Library used for creating multi dimensional array.
Has bindings of C++.

In [1]:
import numpy as np

In [9]:
#list:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
#converting list to array:
my_arr = np.array(my_list) #1-D array

In [10]:
my_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
#type of array:
type(my_arr)

numpy.ndarray

In [12]:
#shape of array:
my_arr.shape

(8,)

#### Multidimensional array:

In [18]:
my_list1 = [1, 2, 3, 4, 5, 6, 7, 8]
my_list2 = [6, 5, 2, 3, 1, 9, 0, 8]
my_list3 = [7, 7, 5, 7, 6, 15, 7, 16]
arr = np.array([my_list1,my_list2, my_list3]) #2-D array


In [19]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 6,  5,  2,  3,  1,  9,  0,  8],
       [ 7,  7,  5,  7,  6, 15,  7, 16]])

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr.shape

(3, 8)

In [23]:
# Reshaping Array:
arr.reshape(6, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 6,  5,  2,  3],
       [ 1,  9,  0,  8],
       [ 7,  7,  5,  7],
       [ 6, 15,  7, 16]])

#### Retrieving Data - Indexing

In [24]:
arr = np.array([1, 2, 3, 5, 6, 8, 9])

In [25]:
arr

array([1, 2, 3, 5, 6, 8, 9])

In [26]:
arr[4]

6

In [27]:
#Indexing in 2-D:
arr = np.array([my_list1,my_list2, my_list3])

In [28]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 6,  5,  2,  3,  1,  9,  0,  8],
       [ 7,  7,  5,  7,  6, 15,  7, 16]])

In [29]:
arr[:,:] #all elements

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 6,  5,  2,  3,  1,  9,  0,  8],
       [ 7,  7,  5,  7,  6, 15,  7, 16]])

In [30]:
arr[0:2,]

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [6, 5, 2, 3, 1, 9, 0, 8]])

In [31]:
arr[:,2:]

array([[ 3,  4,  5,  6,  7,  8],
       [ 2,  3,  1,  9,  0,  8],
       [ 5,  7,  6, 15,  7, 16]])

In [32]:
arr[0:2,0:2]

array([[1, 2],
       [6, 5]])

In [33]:
arr[1:,3:]

array([[ 3,  1,  9,  0,  8],
       [ 7,  6, 15,  7, 16]])

In [38]:
#Inbuilt functions in Numpy:
arr = np.arange(7,20) #creates 1-D array of this range

In [39]:
arr

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
arr = np.arange(8, 50, step=3) #with gap of 3 b/w each elements

In [41]:
arr

array([ 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [43]:
k= np.linspace(1, 20, 100) #start, stop, no.of points

In [44]:
k

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

#### Copy functions:

In [45]:
arr = np.array([my_list1,my_list2, my_list3])

In [46]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 6,  5,  2,  3,  1,  9,  0,  8],
       [ 7,  7,  5,  7,  6, 15,  7, 16]])

In [58]:
arr[2:] = 100 #broadcasting

In [59]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [  6,   5,   2,   3,   1,   9,   0,   8],
       [100, 100, 100, 100, 100, 100, 100, 100]])

In [60]:
arr1 = arr

In [61]:
arr1

array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [  6,   5,   2,   3,   1,   9,   0,   8],
       [100, 100, 100, 100, 100, 100, 100, 100]])

In [62]:
arr1[2:] = 500

In [63]:
arr1

array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [  6,   5,   2,   3,   1,   9,   0,   8],
       [500, 500, 500, 500, 500, 500, 500, 500]])

In [64]:
arr # changing one will change other too

array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [  6,   5,   2,   3,   1,   9,   0,   8],
       [500, 500, 500, 500, 500, 500, 500, 500]])

In [65]:
#as array is reference type.
arr1 = arr.copy()
arr


array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [  6,   5,   2,   3,   1,   9,   0,   8],
       [500, 500, 500, 500, 500, 500, 500, 500]])

In [66]:
arr1

array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [  6,   5,   2,   3,   1,   9,   0,   8],
       [500, 500, 500, 500, 500, 500, 500, 500]])

In [69]:
arr1[2:] = 1000

In [70]:
arr1

array([[   1,    2,    3,    4,    5,    6,    7,    8],
       [   6,    5,    2,    3,    1,    9,    0,    8],
       [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]])

In [71]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [  6,   5,   2,   3,   1,   9,   0,   8],
       [500, 500, 500, 500, 500, 500, 500, 500]])

#### Operations in NUMPY

In [72]:
val = 2
arr < 2

array([[ True, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False,  True, False],
       [False, False, False, False, False, False, False, False]])

In [73]:
arr*2

array([[   2,    4,    6,    8,   10,   12,   14,   16],
       [  12,   10,    4,    6,    2,   18,    0,   16],
       [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]])

In [74]:
arr/2

array([[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ],
       [  3. ,   2.5,   1. ,   1.5,   0.5,   4.5,   0. ,   4. ],
       [250. , 250. , 250. , 250. , 250. , 250. , 250. , 250. ]])

In [75]:
arr%2

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [76]:
#To get elements or conditions for array:
arr[arr<2]

array([1, 1, 0])

In [77]:
arr[arr<500]

array([1, 2, 3, 4, 5, 6, 7, 8, 6, 5, 2, 3, 1, 9, 0, 8])

#### Creating arrays:

In [78]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [79]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [80]:
np.ones((8,10),dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### Random Distribution:

In [81]:
np.random.rand(3,3) #0-1

array([[0.35729593, 0.02939954, 0.56948561],
       [0.37857316, 0.85217655, 0.23011083],
       [0.96020477, 0.80829791, 0.80479209]])

In [82]:
np.random.randn(4,4)

array([[-0.52872824,  0.10108628, -0.29774435,  0.40773849],
       [-0.26700869,  0.45685622,  0.01801485,  1.25047787],
       [-0.03628801,  1.90143299, -0.8870574 ,  1.49540376],
       [ 0.10400877,  0.02294878,  1.75656771,  0.61370936]])

In [89]:
np.random.randint(0,100,12).reshape(4,3)

array([[35, 68, 92],
       [83, 55, 15],
       [24, 37, 22],
       [57, 70, 78]])

In [91]:
np.random.random_sample((6,9))

array([[0.36405626, 0.42267463, 0.19354778, 0.41916749, 0.3197077 ,
        0.48647152, 0.65805946, 0.77636688, 0.62060142],
       [0.15445483, 0.64928573, 0.64902622, 0.87549057, 0.5734636 ,
        0.2988745 , 0.65191365, 0.73327075, 0.7113618 ],
       [0.00499044, 0.08582632, 0.05722453, 0.49661549, 0.76132334,
        0.93050119, 0.02079399, 0.28724743, 0.77874742],
       [0.27966046, 0.8468409 , 0.31748485, 0.74864495, 0.23404772,
        0.67103692, 0.37166752, 0.99045057, 0.4383064 ],
       [0.31286393, 0.59918307, 0.38566972, 0.07017409, 0.24426882,
        0.70120476, 0.61771789, 0.30678178, 0.82276986],
       [0.97526902, 0.4048246 , 0.58291783, 0.45954749, 0.17099071,
        0.92806533, 0.77787235, 0.29819756, 0.15394338]])